### ISSUE TITLE
Cost of the Base is not applicable to all brands

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/vgc#27]
The (optional) Base doesn't apply to Deponti (61 products) or Lugarde ( 1 draft ).

### Requirement
- Do not offer the option to customise the base for any product which is part of the Deponti brand.

### Proposed solution

- [ ] A quick and dirty hard coded solution for products in the Deponti brand
- [ ] or a setting by product indicating if the Base options should be displayed. 
- [x] or a setting for each Brand indicating if Base options are applicable. 

### Current implementation

- The prices for Bases are defined in the global Options ( page=acf-options - Global base size table ). 
- The Base section display is implemented in `template-parts/shop/addons/base-addon.php`

The Deponti brand, post ID 7603, currently has a slug of `passmores-copy`. 
That's probably not good for SEO. 
The Lugarde brand, is post ID 2330.

### Investigation

- Simplest solution is a quick and dirty solution in a new function called `vgc_offer_base_options()` which will return true if the base options are to be offered for the product, false otherwise.
- This function to be called from `addons-main.php`

Side note: For all  61 of the Deponti products there are two installation options shown. The first is labelled **Price on enquiry**, the second says it's FREE.

**Comment by bobbingwide** [comment]
I implemented the quick and dirty solution. The preferred option is the 3rd - a setting indicating if base options are available.
The field will default to true for all brands and needs to be set to false for Deponti.

**Comment by bobbingwide** [comment]
With PHP 8 it appears that when I update a Brand which mostly had unset values for its fields, it now creates post meta data which didn't previously exist. The fields are set to either null or blank strings.  

A non-numeric value for delivery costs causes a Fatal error in the front end.

<b>Fatal error</b>:  Uncaught TypeError: define_addons_by_postcode::getDeliveryCost(): Return value must be of type int, string returned in C:\apache\htdocs\wordpress\wp-content\themes\vgc\woocommerce\inc\classes\define-addons-by-postcode.php:228
Stack trace:
```
#0 C:\apache\htdocs\wordpress\wp-content\themes\vgc\template-parts\shop\addons\delivery-addon.php(6): define_addons_by_postcode-&gt;getDeliveryCost()
#1 C:\apache\htdocs\gardenvista\wp-includes\template.php(772): require('C:\\apache\\htdoc...')
#2 C:\apache\htdocs\gardenvista\wp-includes\template.php(716): load_template('C:\\apache\\htdoc...', false, Array)
#3 C:\apache\htdocs\gardenvista\wp-includes\general-template.php(204): locate_template(Array, true, false, Array)
#4 C:\apache\htdocs\wordpress\wp-content\themes\vgc\template-parts\shop\addons-main.php(131): get_template_part('/template-parts...', 'addon')
#5 C:\apache\htdocs\gardenvista\wp-includes\template.php(772): require('C:\\apache\\htdoc...')
#6 C:\apache\htdocs\gardenvista\wp-includes\template.php(716): load_template('C:\\apache\\htdoc...', false, Array)
#7 C:\apache\htdocs\gardenvista\wp-includes\general-template.php(204): locate_template(Array, true, false, Array)
#8 C:\apache\htdocs\wordpress\wp-content\themes\vgc\woocommerce\content-single-product.php(241): get_template_part('/template-parts...', 'main')
#9 C:\apache\htdocs\gardenvista\wp-includes\template.php(772): require('C:\\apache\\htdoc...')
#10 C:\apache\htdocs\gardenvista\wp-content\plugins\woocommerce\includes\wc-core-functions.php(284): load_template('C:\\apache\\htdoc...', false)
#11 C:\apache\htdocs\gardenvista\wp-content\plugins\woocommerce\templates\single-product.php(37): wc_get_template_part('content', 'single-product')
#12 C:\apache\htdocs\gardenvista\wp-includes\template-loader.php(106): include('C:\\apache\\htdoc...')
#13 C:\apache\htdocs\gardenvista\wp-blog-header.php(19): require_once('C:\\apache\\htdoc...')
#14 C:\apache\htdocs\gardenvista\index.php(17): require('C:\\apache\\htdoc...')
#15 {main}
```
  thrown in <b>C:\apache\htdocs\wordpress\wp-content\themes\vgc\woocommerce\inc\classes\define-addons-by-postcode.php</b> on line <b>228</b><br />

Of the 17 Brands only 6 have a setting for delivery_cost. And of these only one of them is non-zero ( Halls ).

For Passmore I got:

Warning: foreach() argument must be of type array|object, bool given in C:\apache\htdocs\wordpress\wp-content\themes\vgc\template-parts\shop\addons-main.php on line 15

**Comment by bobbingwide** [comment]
Delivered in v1.2.1
